[[sid-8094265_GettingStartedDevelopingApplicationsGuide-GettingstartedwithJBossAS]]

== Getting started with JBoss AS

To run the examples with the provided build scripts, you'll need the following:


* Java 1.6, to run JBoss AS and Maven


* Maven 3, to build and deploy the examples


* the JBoss AS 7 distribution zip


* the JBoss AS 7 quickstarts zip


[TIP]
====
If you already have any of these pieces of software, there is no need to install them again!


====


Choose your Java runtime, and follow their installation instructions. For example, you could choose one of:


*  link:$$http://openjdk.java.net/install/$$[OpenJDK] 


*  link:$$http://www.oracle.com/technetwork/java/javase/index-137561.html$$[Oracle Java SE] 


*  link:$$http://download.oracle.com/docs/cd/E15289_01/doc.40/e15065/toc.htm$$[Oracle JRockit] 

 Follow the official Maven installation guide if you don't already have Maven 3 installed. You can check which version of Maven you have installed (if any) by running mvn --version . If you see a version newer than 3.0.0, you are ready to go. 

You can also deploy the examples using your favorite IDE. We provide instructions for using Eclipse only.

 Now, download JBoss AS 7 from the link:$$http://jboss.org/jbossas/downloads$$[JBoss AS download page] . 


[TIP]
====
JBoss AS 7 offers the ability to manage multiple AS instances from a single control point. A collection of such servers are referred to as members of a "domain", with a single Domain Controller process acting as the management control point. Domains can span multiple physical (or virtual) machines, with all AS instances on a given host under the control of a Host Controller process. The Host Controllers interact with the Domain Controller to control the lifecycle of the AS instances running on that host and to assist the Domain Controller in managing them.

JBoss AS 7 also offers a standalone mode, which is perfect for a single server. We use this throughout the quickstart examples.


====


[[sid-8094265_GettingStartedDevelopingApplicationsGuide-InstallingandstartingJBossASonLinux%2CUnixorMacOSX]]


===Installing and starting JBoss AS on Linux, Unix or Mac OS X

First, let's verify that verify that both Java and Maven are correctly installed. In a console, type:


----
java -version
----

 You should see a version string (at least 1.6.0 ) printed. If not, contact your provider of Java for assistance. Next, type: 


----
mvn --version
----

 You should see a version string (at lest 3.0.0 ) printed. If not, contact the Maven community for assistance. 

 Next, we need to choose a location for JBoss AS to live. By default, JBoss AS 7 will be extracted into jboss-7.x.x.x (where 7.x.x.x matches the version you downloaded): 


----
unzip jboss-7.x.x.x.zip
----

Now, let's start JBoss AS in standalone mode:


----
jboss-7.x.x.x/bin/standalone.sh
----


[TIP]
====
 If you want to stop JBoss AS, simply press Crtl-C whilst the terminal has focus. 


====


 That's it, JBoss AS is installed and running! Visit link:$$http://localhost:8080/$$[] to check the server has started properly. 


[TIP]
====
 You can find the server log for standalone instances in jboss-7.x.x.x/standalone/log/server.log . The Getting Started Guide covers more on configuring logging. 


====


[[sid-8094265_GettingStartedDevelopingApplicationsGuide-InstallingandstartingJBossASonWindows]]


===Installing and starting JBoss AS on Windows

First, let's verify that verify that both Java and Maven are correctly installed. In a Command Prompt, type:


----
java -version
----

 You should see a version string (at least 1.6.0 ) printed. If not, contact your provider of Java for assistance. Next, type: 


----
mvn --version
----

 You should see a version string (at lest 3.0.0 ) printed. If not, contact the Maven community for assistance. 

 Next, we need to choose a location for JBoss AS to live. By default, JBoss AS 7 will be extracted into jboss-7.x.x.x (where 7.x.x.x matches the version you downloaded). Unzip JBoss AS using your tool of choice. 

 Finally, let's start JBoss AS in standalone mode. Locate your JBoss AS installation and run standalone.bat located in bin . 


[TIP]
====
 If you want to stop JBoss AS, simply press Crtl-C whilst the terminal has focus. 


====


 That's it, JBoss AS is installed and running! Visit link:$$http://localhost:8080/$$[] to check the server has started properly. 


[TIP]
====
 You can find the server log for standalone instances in jboss-7.x.x.x/standalone/log/server.log . The Getting Started Guide covers more on configuring logging. 


====


[[sid-8094265_GettingStartedDevelopingApplicationsGuide-StartingJBossASfromEclipsewithJBossTools]]


===Starting JBoss AS from Eclipse with JBoss Tools

You may choose to use Eclipse rather than the command line to run JBoss AS, and to deploy the examples. If you don't wish to use Eclipse, you should skip this section.


[TIP]
====
 In order to use JBoss AS from Eclipse, you must first install JBoss AS for your operating system as  described in <<sid-8094268>> or <<sid-8094269>> . 


====


 In order use JBoss AS from Eclipse, you'll need Eclipse Indigo (Eclipse 3.7) and JBoss Tools 3.3 M2 or newer. If you want to run the quickstarts from Eclipse, you will also need m2eclipse. You can find instructions for installing Eclipse, m2eclipse and JBoss Tools on the link:$$https://www.jboss.org/tools/download/installation/update_3_3.html$$[JBoss Tools Site] . Make sure you install the Maven Support and Web and Java EE Development features. 

 Having successfully installed and started Eclipse, we need to add our JBoss AS instance to it. First, navigate to File -&gt; New -&gt; Other : 

 
.
image::[]

 

Now, locate the New Server Wizard:

 
.
image::[]

 

And choose JBoss AS 7.0:

 
.
image::[]

 

 Hit Next &gt; , and locate the JBoss AS 7 installation by clicking on Browse ... : 

 
.
image::[]

 

Now, choose the JBoss AS 7 installation directory:

 
.
image::[]

 

 Assuming you selected a valid installation, Eclipse should now allow you to hit Finish : 

 
.
image::[]

 

Now, let's start JBoss AS from Eclipse. If you previously started JBoss AS from the command line, you should stop it there first.

 First, we need to make sure the Server tab is on view. Open the Window -&gt; Show View -&gt; Other... dialog: 

 
.
image::[]

 

 And select the Server view: 

 
.
image::[]

 

 You should see the Server View appear with the JBoss AS server: 

 
.
image::[]

 

 Now, we can start the server. Right click on the server in the Server view, and select Start : 

 
.
image::[]

 


[TIP]
====
 If you want to debug your application, you can simply select Debug rather than Start . This will start the server in debug mode, and automatically attach the Eclipse debugger. 


====


 You'll see the server output in the Console : 

 
.
image::[]

 

That's it, we now have the server up and running in Eclipse!

[[sid-8094265_GettingStartedDevelopingApplicationsGuide-ImportingthequickstartsintoEclipse]]


===Importing the quickstarts into Eclipse

In order to import the quickstarts into Eclipse, you will need m2eclipse installed. You can find instructions for installing Eclipse, m2eclipse and JBoss Tools on the JBoss AS site.

 First, choose File -&gt; Import... : 

 
.
image::[]

 

 Select Existing Maven Projects : 

 
.
image::[]

 

 Click on Browse , and navigate to the quickstarts/ directory: 

 
.
image::[]

 

 Finally, make sure all 4 quickstarts are found and selected, and click Finish : 

 
.
image::[]

 

Eclipse should now successfully import 4 projects:

 
.
image::[]

 

It will take a short time to import the projects, as Maven needs to download the project's dependencies from remote repositories.

[[sid-8094265_GettingStartedDevelopingApplicationsGuide-ManagingJBossApplicationServer]]


===Managing JBoss Application Server

 Here we will quickly outline how you can access both the command line interface and the web management interface for managing JBoss AS. Detailed information for both can be found in the link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=8094211$$[Admin Guide] . 

 When the server is running, the web management interface can be accessed at link:$$http://localhost:9990/console$$[] . You can use the web management interface to create datasources, manage deployments and configure the server. 

JBoss AS also comes with a command line interface. To run it on Linux, Unix or Mac, execute:


----
jboss-7.x.x.x/bin/jboss-admin.sh --connect
----

Or, on Windows:


----
jboss-7.x.x.x/bin/jboss-admin.bat --connect
----

 Once started, type help to discover the commands available to you. 

 Throughout this guide we use the jboss-as maven plugin to deploy and undeploy applications. This plugin uses the JBoss AS Native Java Detyped Management API to communicate with the server. The Detyped API is used by management tools to control an entire domain of servers, and exposes only a small number of types, allowing for backwards and forwards compatibility. 

